#ifndef CHANDRA_PHYSICAL_CONSTANTS_H
#define CHANDRA_PHYSICAL_CONSTANTS_H

#include <quantity.h>

namespace chandra
{
namespace units
{

// TODO: THIS FILE NEEDS TO PROVIDE PHYSICAL CONSTANTS BASED ON THE QUANTITY
//  TYPE WITH APPROPRIATE UNITS.  IT WOULD BE BEST TO MAKE THESE WORK AS A
//  PROPERTY OF THE CONSTANT CLASS, BUT IT IS POSSIBLE ALSO TO MAKE IT A
//  METHOD.  EITHER WAY, THESE NEED TO BE CONSISTENT.  SO, IF ONE NEEDS TO BE A
//  METHOD.  THEY ALL NEED TO BE.

// TODO: THIS ALSO MAKES IT SEEM LIKE IT WOULD BE GOOD TO PROVIDE MATHEMATICAL
//  CONSTANTS AS WELL.  AS IT STANDS, THEY WILL BE REPEATED THROUGH DIFFERENT
//  PROJECTS.  THE MATHEMATICAL CONSTANTS SHOULD GO IN CHANDRA MATH THOUGH.
template<typename Value>
struct PhysicConstant
{
  // Speed of Light in a Vacuum
  // Newtonian Constant of Gravity
};

} /*namespace units*/
} /*namespace chandra*/

#endif /*CHANDRA_PHYSICAL_CONSTANTS_H*/
